# GitHub Pages configuration for redirect site
title: "博物馆打卡"
description: "Redirect to museumcheck.cn"

# Use default theme to keep it minimal
theme: minima

# Include important files
include:
  - "404.html"

# Basic settings
encoding: "utf-8"
markdown: kramdown
highlighter: rouge